### ISSUE TITLE
consistency_test.py:TestConsistency.hintedhandoff_test

### ISSUE THREAD

**Issue by ptnapoleon** [riptano/cassandra-dtest#148] opened 2014-12-29 17:28 UTC
https://issues.apache.org/jira/browse/CASSANDRA-8545

**Comment by ptnapoleon** [comment] 2015-01-28 17:57
May be resolved, test doesn't seem to be failing anymore

**Comment by mshuler** [comment] 2015-05-01 03:24
Looks like it has be OK lately, and 8545 was closed "Cannot Reproduce". Closing.

**Closed** 2015-05-01 03:25 UTC
Labels: 2.0, Failing Test
